name: fetch
on:
  push:
    paths-ignore:
      - "**.json"
  schedule:
    - cron: "00 */1 * * *"
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
    # - name: Install JQ
      # run: sudo apt-get install -y jq
    - name: Fetch Data
      run: source fetch
    - name: Push Changes
      continue-on-error: true
      run: |-
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "update data"
        git pull
        git push

